# Copyright © 2017 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: MIT
---

- block:

  - include: check-vic-fileserver.yml

  - name: Ensure install root exists
    file:
      dest: "{{ vic_install_path }}"
      state: directory
      recurse: yes

  - name: Make temp directory
    file:
      dest: "{{ vic_tmp }}"
      state: directory
    become: no
    delegate_to: localhost

  - debug: msg="Downloading vic engine from {{ vic_download_url }}"
  - name: Download vic-engine release archive to ansible host
    get_url:
      url: "{{vic_download_url}}"
      dest: "{{vic_tmp}}/vic-{{ vic_version }}.tar.gz"
      validate_certs: "{{ vic_download_validate_certs }}"
    delegate_to: localhost
    become: no

  - name: Push binary to hosts and extract
    unarchive:
      src: "{{vic_tmp}}/vic-{{ vic_version }}.tar.gz"
      dest: "{{ vic_install_path }}"
      remote_src: False

  - name: Link vic-machine into place
    file:
      src: "{{ vic_install_path }}/vic/vic-machine-{{ ansible_system|lower }}"
      dest: /bin/{{ vic_machine_bin }}
      state: link

  when: "vic_version_found|failed or vic_version not in vic_version_found.stdout"
