# Copyright © 2017 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: MIT
---

- name: Check that the OVA exists
  stat:
    path: "{{ vic_ova_path }}"
    get_checksum: no
    get_md5: no
  become: no
  delegate_to: localhost
  register: stat_result

#- name: Fail early when OVA is missing
#  assert:
#    that: "stat_result.stat.exists == True"
#    msg: "You must provide the vic OVA at {{ vic_ova_path }}"

- include: check-vic-fileserver.yml

- block:
  - name: Remember that the OVA is being installed
    set_fact:
      vic_installed_ova: True

  - name: Make temp directory
    file:
      dest: "{{ vic_tmp }}"
      state: directory

  - name: Copy OVA to remote host
    copy:
      src:  "{{ vic_ova_path }}"
      dest: "{{ vic_tmp }}/{{ vic_ova_path | basename}}"

  - name: Set OVA options
    template:
      src: vic-spec.json.j2
      dest: "{{ vic_tmp }}/vic.spec.json"

  - name: Deploy OVA
    environment:
      GOVC_DATASTORE: "{{ vic_datastore }}"
      GOVC_HOST: "{{ mgmt_vc }}"
      GOVC_URL: "https://{{ mgmt_vc }}/sdk"
      GOVC_INSECURE: True
      GOVC_DATACENTER: "{{ mgmt_vc_datacenter }}"
      GOVC_USERNAME: "{{ mgmt_vc_username }}"
      GOVC_PASSWORD: "{{ mgmt_vc_password }}"
      GOVC_CLUSTER: "{{ mgmt_vc_cluster }}"
    shell: govc import.ova -options="{{ vic_tmp }}/vic.spec.json" "{{ vic_tmp }}/{{ vic_ova_path | basename}}"
    register: vic_ova_deploy_result
    changed_when: no
    failed_when: >
      vic_ova_deploy_result |failed
      and "The name 'vic' already exists." not in vic_ova_deploy_result.stderr
    tags:
      - skip_ansible_lint

  when: >
    (ova_fileserver_output |failed
    or vic_version not in ova_fileserver_output.content)
    and stat_result.stat.exists == True
